package com.github.hornta.sassy_spawn;

public enum ConfigKey {
  LANGUAGE,
  FIRST_JOIN_SPAWN,
  ON_DEATH_SPAWN,
  RESPAWN_AT_BED,
  ALLOW_SPAWN_WHEN_FALLING,
  ALLOW_SPAWN_WHEN_TARGETED,
  TARGETED_COOLDOWN,
  ALLOW_SPAWN_WHEN_DAMAGED,
  DAMAGED_COOLDOWN,
}